version: "2"
services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  alumno:
    container_name: alumno
    restart: always
    build: .
    environment:
      - DOCKER=true
    depends_on:
      - "mongo"
    command: ["./wait-for-it.sh", "-t", "5", "localhost:27017", "--", "node", "index.js"]
    ports:
      - "3050:3050"
    links:
      - mongo
